/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "-== Coming Soon ==--": "-== 即将推出 ==--",
    ". Please check in your": ". 请检查您的",
    ". You can use orbs in artifact menu.": ". 您可以在神器菜单中使用宝珠。",
    "% DPC Boost": "% DPC 提升",
    "% DPS Boost": "% DPS 提升",
    "% Drop Coin Boost": "% 掉落金币提升",
    "% HP": "％ 生命值",
    "1. Add highest stage info": "1.添加最高阶段信息",
    "1. Auto Progress switch button. If you are setting it on, you can progress further automatically": "1.自动进度切换按钮。 如果您正在设置它，您可以自动进一步前进",
    "Yes, Unlock It": "是的，解锁它",
    "Yes, Use It": "是的，使用它",
    "Yes, Withdraw All": "是的，全部撤回",
    "You can continue the training again later, but your elite has to wait next prestige to return dungeon adventure.": "您可以稍后再继续训练，但您的精英必须等待下一次声望才能返回地牢冒险。",
    "You can doing prestige right now. Go to hero tab and click prestige button or you can click prestige button below.": "你现在可以做声望了。转到英雄选项卡并单击声望按钮，或者您可以单击下面的声望按钮。",
    "You can see all your statistic about your account": "您可以查看有关您帐户的所有统计信息",
    "You don't have enough orbs to unlock artifact.": "您没有足够的宝珠来解锁神器。",
    "You have successfully purchased the": "您已成功购买",
    "You will loose all the progress and your pet need to wait half of the rest adventure time.": "您将失去所有进度，您的宠物需要等待一半的休息冒险时间。",
    "Your": "您的",
    "Your feedback and suggestion are very helpful to make this game better.": "您的反馈和建议对让这款游戏变得更好很有帮助。",
    "Your ID": "你的身份证",
    "Your ID : ": "你的身份证 ：",
    "Your pet adventure are over.": "你的宠物冒险结束了。",
    "Special Force - ": "特种部队 -",
    "Special Force Lv": "特种部队 Lv",
    "Stage  ": "阶段",
    "Start All ": "开始所有",
    "Start The Game": "开始游戏",
    "Statistic": "统计",
    "Status : ": "状态 ：",
    "Task": "任务",
    "Tavern": "酒馆",
    "Temple": "寺庙",
    "Thank you for playing Kuro Idle Dungeon": "感谢您玩 无尽的地下城",
    "Thank you for playing Kuro Idle Dungeon. It's still in early stage. Your feedback and suggestion are very helpful to make this game better.": "感谢您玩 无尽的地下城。它仍处于早期阶段。您的反馈和建议对让这款游戏变得更好很有帮助。",
    "This is your Achievement Area": "这是你的成就区",
    "This is your Artifact Area": "这是你的神器区",
    "This is your Barracks & Training Ground Area": "这是你的兵营和训练场区",
    "This is your Companion Area": "这是您的伴侣区",
    "This is your Dropdown Menu Area": "这是您的下拉菜单区",
    "This is your Dungeon Area": "这是你的地牢区域",
    "This is your Elite Area": "这是您的精英区",
    "This is your export / import save file area": "这是您的导出/导入保存文件区域",
    "This is your Hero Area. You'll automatically switch to hero, elite & skill area only for first time play.": "这是你的英雄区。您只会在第一次玩时自动切换到英雄、精英和技能区。",
    "This is your House / Dwellers Area (still under development": "这是您的房屋/居民区（仍在开发中",
    "This is your Pet Cage & Adventure Area": "这是您的宠物笼和冒险区",
    "This is your Profile Area": "这是您的个人资料区",
    "This is your Setting Area": "这是您的设置区域",
    "This is your Shop Area": "这是您的商店区域",
    "This is your Skill Area": "这是你的技能领域",
    "This is your Statistic Area": "这是您的统计区域",
    "This is your Task Area": "这是你的任务区",
    "This is your Temple / Gods & Goddess Area": "这是你的寺庙/神与女神区",
    "Token": "代币",
    "Token : ": "代币：",
    "token to": "代币",
    "token to get": "获得代币",
    "Total Artifact Unlock": "总神器解锁",
    "Total Click": "总点击次数",
    "Total Coin Percentage": "总金币百分比",
    "Total DPC Percentage": "总 DPC 百分比",
    "Total DPS Percentage": "总 DPS 百分比",
    "Total Gain ": "总获得的 ",
    "Total Orbs Percentage": "总球百分比",
    "Total Prestige": "总声望",
    "Total Spent ": "总花费",
    "Total Spent Orbs": "总消耗球",
    "Total Yield : ": "总产量：",
    "Tower": "塔",
    "Town": "镇子",
    "Training Ground": "训练场",
    "Treasure": "宝藏",
    "Tutorial": "教程",
    "Tutorial - Read Until End Of Tutorial": "教程 - 阅读直到教程结束",
    " Artifact": "神器",
    " at hero level ": "在英雄级别",
    " Elite at Thief level 20": "精英在盗贼等级 20",
    " Next Skill at stage 101": "下一个技能在第 101 阶段",
    " Next Skill at stage 81": "下一个技能在第 81 阶段下一个技能",
    " Prestige at stage 100": "声望在第 100 阶段",
    " Skill at stage": "技能在阶段",
    " this Companion at stage ": "此同伴在阶段",
    " this companion at stage 200": "此同伴在第 200 阶段",
    " this equipment at stage 225": "此装备在阶段 225",
    " Watch Tower at": "瞭望塔",
    "Update Profile": "更新配置文件",
    "Upgrade Artifact": "升级神器",
    "Use Item": "使用物品",
    "Use Orbs Now": "立即使用宝珠",
    "Use Skill - Ready To Use": "使用技巧 - 准备使用",
    "Use Token": "使用代币",
    "View complete ability list at our": "在我们的查看完整的能力列表",
    "View complete artifact list at our": "在我们的查看完整的工件列表",
    "View complete companion list at our": "在我们的查看完整的伴侣列表",
    "View complete elite list at our": "在我们的查看完整的精英名单",
    "View complete gods / goddess list at our": "在我们的查看完整的神/女神列表",
    "View complete pet & adventure area list at our": "在我们的查看完整的宠物和冒险区域列表",
    "View complete skill list at our": "在我们的查看完整的技能列表",
    "View Devlog": "查看开发日志",
    "Warehouse": "仓库",
    "Warning": "警告",
    "Weekly": "每周",
    "Welcome to Kuro Idle Dungeon": "欢迎来到 无尽的地下城",
    "What is your kingdom name ?": "你的王国叫什么名字？",
    "Which artifact do you want to unlock ? (": "你想解锁哪个神器？ (",
    "Witchcraft": "巫术",
    "World": "世界",
    "x orbs.": "x 宝珠。",
    "Yes": "是的",
    "Yes, Buy It": "是的，买它",
    "Yes, Cancel It": "是的，取消它",
    "Yes, Clear Tower": "是的，透明塔",
    "Yes, Confirm": "是的，确认",
    "Yes, Do It": "是的，请动手",
    "Yes, Exchange It": "是的，交换它",
    "Yes, Go Adventure": "是的，去冒险",
    "Yes, I Am": "我是",
    "Yes, I Must Retreat": "是的，我必须撤退",
    "for": "为了",
    "Format Number": "格式编号",
    "Gender": "性别",
    "Get Coin": "获取金币",
    "Get Orbs": "获取宝珠",
    "gods fragment?": "神碎片？",
    "Here are new features at v": "以下是 v 的新功能",
    "Hero": "英雄",
    "Highest DPC": "最高 DPC",
    "Highest DPS": "最高DPS",
    "Highest Elite Level": "最高精英等级",
    "Highest Hero Level": "最高英雄等级",
    "Highest Stage": "最高阶段",
    "Highest Weapon Level": "最高武器等级",
    "House": "房子",
    "How many": "多少",
    "How many tower key do you want to use ?": "你想用多少塔钥匙？",
    "I'll Do Later": "我稍后再做",
    "I'll Use Later": "我以后用",
    "I'm Sure": "我确定",
    "Idle Progress": "空闲进度",
    "Import Data": "导入数据",
    "Increase 1 Gods Slot": "增加1个神槽",
    "Increase 100% All Boost": "增加 100% 全部增益",
    "Increase 100% ": "增加 100%",
    "Increase 100% DPC": "增加 100% DPC",
    "Increase 100% DPS": "增加 100% DPS",
    "Increase 100% Orbs": "增加 100% 宝珠",
    "Info": "信息",
    "info for more detail": "更多详细信息",
    "info menu": "信息菜单",
    "is over. Please take your reward !": "结束了。请收下你的奖励！",
    "key do you want to buy ?": "你要买钥匙吗？",
    "Kill Boss Enemy": "杀死 Boss 敌人",
    "Kill Normal Enemy": "杀死普通敌人",
    "King": "国王",
    "King / Queen": "皇太后",
    "Kuro Idle Dungeon": "无尽的地下城",
    "Last Warning! All your data will be reset. Are you sure ?": "最后一次警告！您的所有数据都将被重置。你确定吗 ？",
    "Later": "之后",
    "level ": "等级",
    "Level Up x": "升级 x",
    "Loading your idle progress, please wait...": "正在加载您的空闲进度，请稍候...",
    "Lucky Coin - ": "幸运币 -",
    "Lucky Coin Lv": "幸运币 Lv",
    "Max": "最大",
    "Max Rounded Upgrade": "最大全面升级",
    "menu": "菜单",
    "Milk": "牛奶",
    "Monthly": "月度",
    "Multiplier": "乘数",
    "My Mistake": "我的错",
    "Next": "下一个",
    "No": "不",
    "No Ticket": "没有票",
    "No, Abort Abort": "不，中止 中止",
    "No, Cancel it": "不，取消它",
    "No, Cancel It": "不，取消它",
    "No, Don't Buy It": "不，不要买",
    "No, Don't Cancel": "不，不要取消",
    "No, Don't Clear Tower": "不，不要清除塔",
    "No, Don't Do It": "不，不要这样做",
    "No, Don't Import": "不，不要导入",
    "No, Don't Skip It": "不，不要跳过它",
    "No, Don't Use It": "不，不要使用它",
    "No, Don't Withdraw": "不，不要撤回",
    "No, I'll do later": "不，我稍后再做",
    "No, I'll Take Later": "不，我稍后再拿",
    "No, I'll Unlock Later": "不，我稍后解锁",
    "No, Keep Battling": "不，继续战斗",
    "No, My Mistake": "不，我的错误",
    "No, Stop Now": "不，现在停止",
    "No, Wait Here": "不，在这里等",
    "Normal Prestige": "普通声望",
    "Offline Duration": "离线时长",
    "Offline Gain ": "离线增益",
    "Offline Progress": "离线进度",
    "Ok": "好的",
    "Online Duration": "在线时长",
    "Online Gain ": "在线获得",
    "Open Backpack": "打开背包",
    "Or, re-roll another artifact. (": "或者，重新滚动另一个神器。 (",
    "orbs": "宝珠",
    "Orbs": "宝珠",
    "Other": "其他",
    "partner?": "伙伴？",
    "Permanent - ": "永久 -",
    "pet adventure at": "宠物冒险",
    "pet at": "宠物在",
    "Play": "玩",
    "Played Since": "玩过",
    "Please take your reward !": "请收下你的奖励！",
    "Pouch of Coin (1 Hour Coin) - ": "金币袋（1小时金币）-",
    "Power Shot - ": "强力射击 -",
    "Power Shot Lv": "强力射击 Lv",
    "7. Your 1st adventure passive buff. It will be activate when the companion level is a multiple of 5": "7.你的第一次冒险被动增益。同伴等级为5的倍数时激活",
    "7. Your 1st gods benefit description": "7.你的第一神福利说明",
    "7. Your current elite damage per second": "7.你当前的每秒精英伤害",
    "7. Your hero damage. (+2) means your additional damage in next upgrade": "7.你的英雄伤害。 (+2) 表示你在下一次升级中的额外伤害",
    "8 Hours - ": "8小时 -",
    "8. Ability point currently held and can be user to increase ability accuracy and damage": "8.当前持有的技能点，可以供用户增加技能精准度和伤害",
    "8. Activate button to activate the active damage and active buff": "8.激活按钮激活主动伤害和主动buff",
    "8. Green button indicate your skill is ready to use": "8.绿色按钮表示您的技能已准备好使用",
    "8. Level up button for upgrade your hero": "8.升级你的英雄升级按钮",
    "8. Sell button to sell your artifact and you'll get half orbs that already spent for that artifact": "8. 出售您的神器的按钮，您将获得已经为该神器花费的一半宝珠",
    "8. Show your dungeon area": "8. 显示你的地牢区域",
    "8. Symbol that shows that you have completed the task": "8. 表示您已完成任务的符号",
    "8. You can trade 300 token for permanent buff": "8.您可以交易300代币以获得永久buff",
    "8. Your 1st adventure area. 1 hour indicate time needed to complete the adventure": "8. 你的第一个冒险区。 1 小时表示完成冒险所需的时间",
    "8. Your 1st current fragment / target fragment to level up gods / goddess": "8.你的第一个当前碎片/目标碎片升级神/女神",
    "8. Your current orbs. Will show after first prestige": "8. 你当前的宝珠。将在第一次声望后显示",
    "9. Accumulate training time for current ability": "9.为当前能力积累训练时间",
    "9. Hit enemy button to attack enemy with your DPC": "9.点击敌人按钮用你的DPC攻击敌人",
    "9. Reincarnate button to increase gods / goddess max level": "9.转世按钮增加神/女神最高等级",
    "9. Show next skill unlock requirement": "9.显示下一个技能解锁要求",
    "9. Show your task area": "9. 展示你的任务区域",
    "9. You current active companion. Will shown at the hero area in dungeon adventure": "9. 您当前的活跃伙伴。将在地牢冒险的英雄区展示",
    "9. Your 1st adventure area description": "9. 你的第一个冒险区域描述",
    "9. Your current weapon level": "9.你当前的武器等级",
    "ability for": "能力",
    "Achievement": "成就",
    "Activate Companion first at companion menu": "首先在同伴菜单中激活同伴",
    "Adventure": "冒险",
    "Adventure Area": "冒险区",
    "adventure at": "冒险在",
    "All Skill - ": "所有技能 -",
    "All your data will be reset. Are you sure ?": "您的所有数据都将被重置。你确定吗 ？",
    "Are you sure want to": "你确定要",
    "Are you sure want to cancel": "您确定要取消吗",
    "Are you sure want to collect reward": "你确定要领取奖励吗",
    "Are you sure want to exchange": "你确定要兑换吗",
    "Are you sure want to import data? Your existing save data will be replaced!": "您确定要导入数据吗？您现有的保存数据将被替换！",
    "Are you sure want to prestige? You will get": "你确定要声望？你会得到",
    "Are you sure want to re-roll another artifact for": "你确定要重新滚动另一个神器",
    "Are you sure want to retreat form the tower battle? You won't loose the key.": "你确定要从塔战中撤退吗？你不会松开钥匙。",
    "Are you sure want to save the ability changes ?": "您确定要保存能力更改吗？",
    "Are you sure want to sell": "你确定要出售",
    "Are you sure want to skip the story ?": "你确定要跳过这个故事吗？",
    "Are you sure want to spend": "你确定要花吗",
    "Are you sure want to start adventure with your": "您确定要开始冒险吗？",
    "Are you sure want to start training": "你确定要开始训练吗",
    "Are you sure want to stop training": "你确定要停止训练吗",
    "Are you sure want to unlock": "你确定要解锁吗",
    "Are you sure want to use": "你确定要使用",
    "Are you sure want to withdraw all token from the bank ?": "您确定要从银行提取所有代币吗？",
    "Army Camp": "军营",
    "Army HP Icon ": "陆军 HP 图标",
    "Artifact": "神器",
    "Artifact (": "神器（",
    "Artifact Power %": "神器功率%",
    "Auto Clicker - ": "自动点击器 -",
    "Auto Clicker Lv": "自动点击器 等级",
    "Auto Continue Training": "自动继续培训",
    "Auto Progress": "自动进度",
    "Auto Sell ": "自动出售",
    "Backpack": "背包",
    "Bag of Coin (6 Hours Coin) - ": "一袋金币（6小时金币）-",
    "Bank": "银行",
    "Banshees": "女妖",
    "barracks": "军营",
    "Barracks": "兵营",
    "Billionaire - ": "亿万富翁 -",
    "Buy": "买",
    "Buy 1 Instant ": "购买 1 个即时",
    "Buy 1 Skill Ticket": "购买 1 张技能券",
    "Cactus": "仙人掌",
    "Cage": "笼",
    "Cancel": "取消",
    "Canteen": "食堂",
    "Cart of Coin (24 Hours Coin) - ": "金币车（24 小时金币） -",
    "Cave": "洞穴",
    "Check In": "签到",
    "Check that your system clock is set to the current date and time before you try again.": "在重试之前检查您的系统时钟是否设置为当前日期和时间。",
    "Chest of Coin (12 Hours Coin) - ": "金币箱（12 小时金币） -",
    "Clear Game": "清除游戏",
    "Close": "关闭",
    "Clover : ": "三叶草：",
    "Coin": "金币",
    "Coin Master ": "金币大师",
    "Collect": "收藏",
    "Collect All ": "收集所有",
    "Collect Reward - 1 Token": "收集奖励 - 1 代币",
    "Congratz for your prestige, you got": "恭喜你的声望，你得到了",
    "Congratz you just unlock your first pet. Do you want to see your pet?": "恭喜你解锁了你的第一只宠物。你想看看你的宠物吗？",
    "Contact Dev": "联系开发",
    "Continue": "继续",
    "Crit Chance Percentage": "暴击率百分比",
    "Crit Damage Percentage": "暴击伤害百分比",
    "Current token : ": "当前代币：",
    "Current Token : ": "当前代币：",
    "Daily": "日常的",
    "Daily Limit (": "每日限额 (",
    "Danger": "危险",
    "16. Gray button indicates your pet adventure is colling down cause of cancel the adventure": "16.灰色按钮表示您的宠物冒险正在崩溃，原因是取消冒险",
    "16. Show your tutorial area": "16.展示你的教程区",
    "17. Show next unlock adventure area requirement": "17.显示下一个解锁冒险区域要求",
    "17. Show your setting area": "17. 显示您的设置区域",
    "17. Time remaining training to move up to the next level. You can click the button to stop the training, and the elapsed time will be saved": "17. 剩余的训练时间以提升到一个新的水平。您可以单击按钮停止训练，并保存经过的时间",
    "18. Choose elite button to show elite list": "18.选择精英按钮显示精英列表",
    "18. You can save game manually. But this game already save automatically every 10 seconds": "18.您可以手动保存游戏。但是这个游戏已经每10秒自动保存一次",
    "19. Elite drop down list that want to train": "19.想要训练的精英下拉列表",
    "19. You can export & import your save game": "19.您可以导出和导入您的保存游戏",
    "2. Add claim all button for achievement": "2. 增加领取全部成就按钮",
    "2. Click start all skill button to run skills simultaneously": "2.点击开始所有技能按钮同时运行技能",
    "2. Download data button, will download your save data to the file": "2.下载数据按钮，将您保存的数据下载到文件中",
    "2. Information for how many free companion that you can get": "2.您可以获得多少免费同伴的信息",
    "2. Show current daily task. Will reset every day at 00:00": "2.显示当前每日任务。将在每天 00:00 重置",
    "2. Show current total soul / target soul to exchange the fragment": "2.显示当前总灵魂/目标灵魂交换碎片",
    "2. Show icon setting. If you choose enable, all the icon will be shown": "2.显示图标设置。如果选择启用，将显示所有图标",
    "2. Show your dropdown adventure menu": "2. 显示您的下拉冒险菜单",
    "2. Show your elite and his status (battling, training, resting). When training, the elite will remove from the dungeon": "2.展示你的精英和他的状态（战斗，训练，休息）。训练时，精英会从地牢中移除",
    "2. Show your elite area": "2.展示你的精英区域",
    "2. Show your next elite unlock requirement": "2.展示你的下一个精英解锁要求",
    "2. Your 1st dwellers ability": "2. 你的第一居民能力",
    "2. Your 1st pet name and level": "2.你的第一个宠物名字和等级",
    "2. Your achievement level": "2. 你的成就水平",
    "2. Your current token.": "2. 您当前的代币。",
    "2. Your custom User Name": "2.您的自定义用户名",
    "2. Your total artifact damage. It will increase your dpc, dps and coin gain from enemy": "2. 你的神器总伤害。它会增加你的dpc，dps和敌人的金币收益",
    "2. Your world stage. You can change stage back to grinding coin": "2. 你的世界舞台。您可以将阶段更改回磨金币",
    "20. Ability drop down list that want to train": "20.想要训练的能力下拉列表",
    "20. You can clear game manually and you'll lost all your data": "20.您可以手动清除游戏，您将丢失所有数据",
    "2022/3/29 10:07:39": "2022/3/29 10:07:39",
    "21. Start training button to start training the selected ability": "21.开始训练按钮开始训练选定的能力",
    "21. You can contact the developer for anything about this game": "21.您可以联系开发者了解有关此游戏的任何信息",
    "22. Click to show dungeon area": "22.点击显示地牢区域",
    "24 Hours - ": "24小时 -",
    "29 March 2022": "2022 年 3 月 29 日",
    "3. Add a lot in game information": "3.在游戏信息中添加大量",
    "3. All the buff from the shop": "3.商店的所有buff",
    "3. Click update profile button to update your profile": "3.单击更新个人资料按钮以更新您的个人资料",
    "3. Drop down list to exchange the soul": "3.下拉列表交换灵魂",
    "3. Format number setting. You can choose format number between exponential or letter": "3.格式编号设置。您可以在指数或字母之间选择格式数字",
    "3. Show current weekly task. Will reset every monday at 00:00": "3. 显示当前每周任务。每周一 00:00 重置",
    "3. Show your dropdown town menu": "3.显示您的下拉城镇菜单",
    "3. Show your skill area": "3.展示你的技能领域",
    "3. Show your strongest elite. You can change the elite order in": "3.展示你最强的精英。您可以更改精英订单",
    "3. Unlock button to unlock new artifact": "3.解锁按钮解锁新神器",
    "3. You can show and hide all the ability of the selected elite": "3.您可以显示和隐藏所选精英的所有能力",
    "3. Your 1st companion": "3. 你的第一个同伴",
    "3. Your 1st Skill": "3. 你的第一技能",
    "3. Your current achievement / next target achievement": "3.您当前的成就/下一个目标成就",
    "3. Your enemy name": "3.你的敌人名字",
    "3. Your export data textarea.": "3.您的导出数据文本区域。",
    "30 Days - ": "30天 -",
    "4. 1st ability of the selected elite. Symbol means you have point to upgrade. 1st number means ability current level, 2nd means ability max level. View complete ability list at our": "4. 选定精英的第一能力。符号表示您有升级点。第一个数字表示能力当前等级，第二个数字表示能力最高等级。在我们的查看完整的能力列表",
    "4. 1st buff that you can trade": "4.你可以交易的第一个buff",
    "4. Auto continue training setting. If you choose enable, after finish current elite ability training, it will automatic start next training": "4.自动继续训练设置。如果选择启用，完成当前的精英能力训练后，将自动开始下一次训练",
    "4. Click collect reward button to get achievement reward": "4.点击领取奖励按钮获得成就奖励",
    "4. Current enemy life / maximum enemy life": "4.当前敌人生命/最大敌人生命",
    "4. Exchange Gods Fragment button to exchange soul to fragment": "4. 神灵碎片兑换按钮，可以将灵魂兑换成碎片",
    "4. Import data button, will import your save data from the import data textarea": "4.导入数据按钮，将从导入数据文本区域导入您的保存数据",
    "4. Show current monthly task. Will reset every 1st date of the month": "4.显示当前每月任务。将在每个月的第一个日期重置",
    "4. Show shopping area": "4.显示购物区",
    "4. Show your active elite ability. See": "4.展现你的主动精英能力。看",
    "4. Show your dropdown other menu": "4. 显示您的下拉菜单",
    "4. Stop enabling auto progress when kill boss": "4.杀死boss时停止自动进度",
    "4. Your 1st artifact level": "4. 你的第一神器等级",
    "4. Your 1st companion active damage": "4.你的第一个同伴主动伤害",
    "4. Your 1st current exp / target exp to level up": "4.你的第一个当前经验/目标经验升级",
    "4. Your 1st Skill Damage. (+1) means your additional damage in next upgrade": "4. 你的第一技能伤害。 (+1) 表示您在下次升级中的额外伤害",
    "4. Your 1st working time the dwellers are running. It will show if your dweller status is working": "4. 居民正在运行的第一次工作时间。它将显示您的居民身份是否有效",
    "5. Achievement level 0 when not taking the reward at all": "5. 完全不领取奖励时成就等级0",
    "5. Current level up multiplier": "5.当前升级乘数",
    "5. Level up button for upgrade your 1st skill": "5.升级按钮用于升级你的第一个技能",
    "5. Offline progress setting. If you choose grind at same area, you won't progress to next stage when offline": "5.离线进度设置。选择同区刷，离线时无法进入下一关",
    "5. Pet Adventure button to start adventure in selected adventure zone": "5.宠物冒险按钮在选定的冒险区域开始冒险",
    "5. Show gods & goddess area": "5. 秀神&女神专区",
    "5. Show your profile area": "5.显示您的个人资料区域",
    "5. Update background & font color": "5.更新背景和字体颜色",
    "5. You can increase ability accuracy with the point that you gain each level. Blue font means the value that have been changes": "5.你可以通过获得每个级别的点来提高能力准确性。蓝色字体表示已更改的值",
    "5. You can trade 4 token for 8 hours buff": "5.你可以交易4个8小时buff",
    "5. Your 1st artifact bonus": "5. 你的第一件神器奖励",
    "5. Your 1st companion passive damage. It will be activate when the companion level is a multiple of 5": "5.你的第一个同伴被动伤害。同伴等级为5的倍数时激活",
    "5. Your current active task. (1 token) means you'll get 1 token if complete the task": "5. 您当前的活动任务。 (1 token) 表示完成任务将获得 1 token",
    "5. Your current damage": "5.你当前的伤害",
    "5. Your import data textarea.": "5.您的导入数据文本区域。",
    "5. Your strongest elite DPS. (+1.1M) means your additional DPS in next upgrade": "5.你最强的精英DPS。 (+1.1M) 意味着你下次升级的额外 DPS",
    "6. Dark mode setting. If you choose enable, dark mode configuration will be activate": "6.暗模式设置。如果选择启用，将激活暗模式配置",
    "6. Detail task description": "6.详细的任务描述",
    "6. Gray button indicate your skill is under cooldown duration": "6.灰色按钮表示你的技能处于冷却时间",
    "6. Level up button for upgrade your elite": "6.升级按钮升级你的精英",
    "6. Show next unlock pet requirement": "6.显示下一个解锁宠物要求",
    "6. Show your statistic area": "6.显示你的统计区域",
    "6. Update better story flow": "6.更新更好的故事流程",
    "6. You can increase ability damage with the point that you gain each level": "6. 每升一级可以增加技能伤害",
    "6. You can trade 10 token for 24 hours buff": "6.您可以交易10个代币以获得24小时buff",
    "6. Your 1st artifact description": "6. 你的第一个神器描述",
    "6. Your 1st companion active buff": "6.你的第一个同伴活跃的buff",
    "6. Your 1st gods name and level / max level. When reach max level, you need to reincarnate to increase max level": "6.你的第一个神名和等级/最高等级。达到最高等级时，您需要转生以提高最高等级",
    "6. Your current coin": "6.您当前的金币",
    "10. Current exp / target exp to level up": "10.当前经验/目标经验升级",
    "10. Deactivate button to deactivate the active damage and active buff": "10.停用按钮可停用主动伤害和主动buff",
    "10. Deactivate button to deactivate the gods / goddess": "10. 停用按钮可停用众神/女神",
    "10. Show your artifact area": "10.展示你的神器区域",
    "10. Your 1st adventure area current exp / target exp to level up": "10.你的第一个冒险区域当前经验/目标经验升级",
    "10. Your weapon damage. (+5) means your additional damage in next upgrade": "10. 你的武器伤害。 (+5) 表示你在下一次升级中的额外伤害",
    "11. Level up button for upgrade your weapon": "11.升级你的武器的升级按钮",
    "11. Save button to save the accuracy / damage that have been changes": "11.保存按钮保存已更改的精度/损坏",
    "11. Show your barracks area": "11. 展示你的兵营区域",
    "11. Summon button to upgrade gods / goddess level": "11.召唤按钮提升神/女神等级",
    "11. Your 1st adventure area pet slot. 1 pet slot indicate you can run 1 pet at same adventure area": "11.您的第一个冒险区宠物槽。 1个宠物槽表示您可以在同一冒险区域运行1只宠物",
    "12. Activate button to activate the gods / goddess": "12.激活按钮激活神/女神",
    "12. Activate button to start the ability damage in dungeon": "12.激活按钮开始在地牢中的能力伤害",
    "12. Show your companion area": "12.显示你的同伴区域",
    "12. Your 1st adventure area bonus coin": "12. 你的第一个冒险区奖金金币",
    "12. Your current companion in adventure. See": "12. 你现在的冒险伙伴。看",
    "13. Deactivate button to stop the ability damage in dungeon": "13.禁用按钮以停止地牢中的能力伤害",
    "13. Show your cage area": "13.展示你的笼子区域",
    "13. Your 1st adventure area bonus exp": "13. 你的第一个冒险区域奖励经验",
    "13. Your current companion benefit.": "13. 您当前的同伴福利。",
    "1. Elite sequence setting. If you choose weakest to strongest, the weakest parner will shown it the top of the list": "1.精英序列设置。如果您选择从最弱到最强，最弱的伙伴将显示在列表顶部",
    "1. Export data button, will export your save data to the export data textarea": "1.导出数据按钮，将您保存的数据导出到导出数据文本区域",
    "1. Show Temple area": "1. 显示寺庙区域",
    "1. Show your barracks area": "1.展示你的兵营区域",
    "1. Show your cage area": "1.展示你的笼子区域",
    "1. Show your current token": "1. 显示您当前的代币",
    "1. Show your dropdown info menu": "1. 显示您的下拉信息菜单",
    "1. Show your elite area": "1.展示你的精英区域",
    "1. Show your hero area": "1.显示你的英雄区域",
    "1. Show your shop area": "1.显示您的商店区域",
    "1. Show your skill area": "1.展示你的技能领域",
    "1. The time it takes to get free ": "1.所需的时间获得免费",
    "1. Your 1st dwellers name and level": "1.您的第一个居民姓名和级别",
    "1. Your achievement name": "1. 你的成就名称",
    "1. Your current orbs. You need orbs to unlock & upgrade artifact": "1.您当前的宝珠。您需要宝珠来解锁和升级神器",
    "1. Your current token. You can trade your token in": "1. 您当前的代币。您可以交易您的代币",
    "1. Your unique User ID": "1. 您的唯一用户 ID",
    "Yes, I Want To See It": "是的，我想看",
    "Yes, Import Data": "是的，导入数据",
    "Yes, Please": "是的，请",
    "Yes, Run Quest": "是的，运行任务",
    "Yes, Save It": "是的，保存",
    "Yes, Skip It": "是的，跳过它",
    "Yes, Start Reincarnating": "是的，开始转世",
    "Yes, Start Training": "是的，开始训练",
    "Yes, Stop Training": "是的，停止训练",
    "Yes, Take It Now": "是的，现在就拿",
    "Your training elite, can't participate in the dungeon adventure.": "你的训练精英，无法参与地下城冒险。",
    "Your Username": "您的用户名",
    "Elite ": "精英",
    "Enable Popup Confirmation": "启用弹出确认",
    "Export / Import": "进出口",
    "Export Data": "导出数据",
    "Export Import Data": "导出导入数据",
    "Filter : ": "筛选 ：",
    "Gods (": "神 （",
    "Gods Slot : ": "众神插槽：",
    "Grim Reaper - ": "死神 -",
    "Kelpie": "凯尔派",
    "level ": "等级",
    "Lucky Coin - ": "幸运币 -",
    "Permanent - ": "永久 -",
    "Pouch of Coin (1 Hour Coin) - ": "金币袋（1小时金币）-",
    "Power Shot - ": "强力射击 -",
    "Prestige": "声望",
    "Prev": "上一页",
    "Profile": "个人资料",
    " Artifact": "神器",
    "Refresh In": "刷新",
    "Refresh In : ": "刷新：",
    "Refrigerator": "冰箱",
    "Role : ": "角色 ：",
    "Rounded Upgrade": "全面升级",
    "Run Skill": "跑技",
    "Save Data Success": "保存数据成功",
    "Save Game": "保存游戏",
    "Save My Kingdom Name": "保存我的王国名称",
    "Sell & Upgrade ": "出售和升级",
    "Set": "放",
    "setting": "环境",
    "Setting": "环境",
    "shop": "商店",
    "Shop": "商店",
    " Artifact": "神器",
    "Show Icon": "显示图标",
    "Show Real Time DPS ": "显示实时DPS",
    "Show Tutorial": "显示教程",
    "Sidebar Menu": "侧边栏菜单",
    "Skip": "跳过",
    "Skip Tutorial": "跳过教程",
    "Sort : ": "种类 ：",
    "Souls with": "灵魂与",
    "Special Force - ": "特种部队 -",
    "Stage  ": "阶段",
    "Status : ": "状态 ：",
    "Token : ": "代币：",
    "Total Yield : ": "总产量：",
    "Unlock at hero level ": "在英雄级别解锁",
    "Unlock this Companion at stage ": "在阶段解锁此同伴",
    "7. Current count task / target to be reached": "7.当前计数任务/要达到的目标",
    "7. Reoder sidebar menu 8. Add in game time 9. A lot bugs fixing, adjustment & improvement": "7. Reoder 侧边栏菜单 8. 增加游戏时间 9. 大量错误修复、调整和改进",
    "7. Show all elite type in this game": "7.在这个游戏中显示所有精英类型",
    "7. Show your achievement area": "7. 展示你的成就领域",
    "7. Show your adventure area": "7. 展示你的冒险区域",
    "7. The elite's time span to release the ability damage": "7.精英释放技能伤害的时间跨度",
    "7. Upgrade button to upgrade your artifact": "7.升级按钮升级你的神器",
    "7. Yellow button indicate your skill is running": "7.黄色按钮表示你的技能正在运行",
    "7. You can trade 250 token for 30 days buff": "7. 30天buff可交易250个代币",
    "Dark Mode": "黑暗模式",
    "Download Data": "下载数据",
    "elite ?": "精英？",
    "Elite Barracks": "精英兵营",
    "Gods (": "神 （",
    "14. Prestige button will appear when you reach stage 100. Prestige will reset your progress but you'll gain orbs": "14.达到100级时会出现声望按钮。声望会重置你的进度，但你会获得宝珠",
    "14. Show your house area": "14.显示你的房子面积",
    "14. Show your training ground area": "14. 展示你的训练场区域",
    "14. Your 1st adventure area adventure pet button. Click to start the adventure of selected pet": "14.你的第一个冒险区冒险宠物按钮。点击开始选择宠物的冒险",
    "15. Show the training slot number. You can expand the slot in future (under development": "15. 显示训练槽号。您可以在将来扩展插槽（正在开发中",
    "15. Show your temple area": "15.展示你的寺庙区域",
    "15. Yellow button indicates your pet adventure is on progress. If you click the button, you will cancel the adventure and you will get half of the adventure time for colling down": "15. 黄色按钮表示您的宠物冒险正在进行中。如果你点击按钮，你将取消冒险，你将获得一半的冒险时间来崩溃",
    "16. Description of the on progress training": "16. 进度培训说明",
    "24 Hours - ": "24小时 -",
    "30 Days - ": "30天 -",
    "6. Your current hero level": "6.你当前的英雄等级",
    "Upgrade ": "升级 ",
    "Watch Tower Lv ": "瞭望塔等级 ",
    "Cut": "砍",
    "Parasite": "寄生虫",
    "Valkyrie": "女武神",
    "Giant": "巨人",
    "Spider": "蜘蛛",
    "Marionette": "傀儡",
    "Witch": "女巫",
    "Tentacle": "触手",
    "End Tutorial": "结束教程",
    "Next →": "下一个 →",
    "Phobos": "火卫一",
    "Congratz, you have successfully performed prestige the first time. Please click use orbs button now": "恭喜，你第一次成功地发挥了威望。 请立即点击使用宝珠按钮",
    "Congratz for your 1st artifact": "恭喜您获得第一件神器",
    "Damage": "伤害",
    "Each artifact will produce artifact power and artifact power will increase the power of DPC, DPS and Gold drop from killing monster": "每件神器都会产生神器威力，神器威力会增加击杀怪物的DPC、DPS和金币掉落",
    "I will come back later if you reach stage 125": "如果你到达第 125 阶段，我会晚点回来",
    "If correct please click yes, if wrong please click no": "如果正确请点击是，如果错误请点击否",
    "Increase Elite DPS 20% / level": "增加精英 DPS 20% / 级",
    "Increase Hero DPC 20% / level": "增加英雄 DPC 20% / 级",
    "Increase Watch Tower DPC 20% / level": "增加瞭望塔 DPC 20% / 级",
    "Name": "姓名",
    "Please choose 1 of the 3 artifacts above as your 1st artifact": "请从上述 3 件神器中选择 1 件作为您的第一件神器",
    "Please confirm whether your choice of artifact is correct or not": "请确认您选择的神器是否正确",
    "Please continue your adventure your highness, and collect as many orbs as possible.": "请继续您的冒险，殿下，并收集尽可能多的宝珠。",
    "Tips: Maximize your elite, hero and watch tower level before prestige to gain more orbs when prestige": "提示：在声望之前最大化你的精英，英雄和瞭望塔等级，以在声望时获得更多宝珠",
    "Type": "类型",
    "unlock artifact button now": "立即解锁神器按钮",
    "Upgrade Fee": "升级费",
    "Upgrade Level": "升级等级",
    "Urumi": "乌鲁米",
    "You can now unlock 1st artifact. Please click": "您现在可以解锁第一个神器。 请点击",
    "All": "全部",
    "Gnolls": "豺狼人",
    "Gnome": "侏儒",
    "Goblin": "地精",
    "Gorgon": "芡实",
    "Gremlin": "小精灵",
    "Grunt": "咕噜声",
    "Harpies": "鹰身女妖",
    "Hedgehog": "刺猬",
    "Hellhound": "地狱犬",
    "Hydra": "九头蛇",
    "Hyena": "鬣狗",
    "Iceworm": "冰虫",
    "Imp": "小鬼",
    "Incubus": "梦魇",
    "Jackal": "豺狼",
    "Kappa": "卡帕",
    "Kishi": "岸",
    "Kraken": "海妖",
    "Ladybug": "瓢虫",
    "Lich": "巫妖",
    "Loch Ness": "尼斯湖",
    "Lunatic": "疯子",
    "Lynx": "猞猁",
    "Magma": "岩浆",
    "Mandrake": "曼德拉草",
    "Manticore": "蝎尾狮",
    "Merman": "人鱼",
    "Nue": "努埃",
    "Nymph": "若虫",
    "Pandora": "潘多拉",
    "Pixie": "小精灵",
    "QQ群号": "QQ群号",
    "Redcap": "红帽",
    "Rocky": "洛基",
    "Salamanders": "蝾螈",
    "Sandworm": "沙虫",
    "Sasquatch": "大脚野人",
    "Satan": "撒但",
    "Satyr": "色狼",
    "Shachihoko": "沙千穗子",
    "Siren": "警笛",
    "Slime": "粘液",
    "Slugger": "重击手",
    "Snake": "蛇",
    "Stinger": "刺",
    "Succubus": "魅魔",
    "Tanuki": "狸猫",
    "Tengu": "天狗",
    "Tigris": "底格里斯",
    "Troll": "巨魔",
    "Vampire": "吸血鬼",
    "Werehog": "狼人",
    "Wisp": "小精灵",
    "Abelisaurus": "阿贝利龙",
    "Abyssbat": "深渊蝙蝠",
    "Ade": "阿德",
    "Alicanto": "阿利坎托",
    "Alligator": "鳄鱼",
    "Anubis": "阿努比斯",
    "Anzu": "安祖",
    "Arachne": "阿拉克内",
    "Armadillo": "犰狳",
    "Baryonyx": "重爪龙",
    "Bigfoot": "大脚",
    "Boar": "公猪",
    "Bomb": "炸弹",
    "Bri": "Bri",
    "Arachnoid": "蜘蛛网",
    "Cupacabra": "杯卡布拉",
    "Enhance Level": "强化等级",
    "Get ": "获得 ",
    "Grade": "年级",
    "Maiden": "少女",
    "Max Value": "最大值",
    "Min Value": "最小值",
    "Ogre": "食人魔",
    "Partner": "伙伴",
    "Satori": "悟",
    "Skeleton": "骨骼",
    "Tower of ": "塔关于",
    "Tower of Force": "力量之塔",
    "Tower of Glory": "荣耀之塔",
    "Tower of Spirit": "精神之塔",
    "Tower of Wealth": "财富之塔",
    "Your backpack is empty": "你的背包是空的",
    "* Will boost monster drop coin by certain": "* 一定会增加怪物掉落金币",
    "* Will boost your current DPC by 50": "* 将你当前的 DPC 提高 50",
    "* Will boost your current DPS by certain": "* 会提升你当前的 DPS",
    "* Will launch current DPC 11 times per second ": "* 每秒将启动当前 DPC 11 次",
    "Are you sure want to use Auto Clicker Ticket ?": "您确定要使用 Auto Clicker Ticket 吗？",
    "Auto Clicker": "自动点击器",
    "Auto Clicker Ticket": "自动点击器票",
    "backpack": "背包",
    "buy 1 Ticket of Auto Clicker": "购买 1 张自动点击器票",
    "Deposit": "订金",
    "Open backpack": "打开背包",
    "Run ": "跑步",
    "Run Auto Clicker Skill immediately.": "立即运行 自动点击器 技能。",
    "Ticket": "票",
    "Use": "使用",
    "Your warehouse is empty": "你的仓库是空的",
    "increase DPS 100% for 8 Hours": "8小时内增加100% DPS",
    "Sprite": "精灵",
    "Wraith": "幽灵",
    "Golem": "魔像",
    "Billionaire Lv": "亿万富翁 等级",
    "Click to Stop - -": "点击停止 - -",
    "Hippogriff": "鹰头马",
    "Sacred Gems": "神圣宝石",
    "Safety Vault": "安全保险库",
    "Shadow Robe": "暗影长袍",
    "Sharp Arrow": "锋利的箭头",
    "Sharp Blade": "锋利的刀片",
    "Sharp Gun": "锋利的枪",
    "Sharp Knuckle": "锋利的指关节",
    "Sharp Rune": "锋利的符文",
    "Sharp Shuriken": "锋利的手里剑",
    "Sharp Sword": "锋利的剑",
    "Sharp Wand": "锋利的魔杖",
    "Shiny Amulet": "闪亮的护身符",
    "Shiny Gems": "闪亮的宝石",
    "Shiny Jewel": "闪亮的珠宝",
    "Shorten Interval Elite DPS 10ms / level": "缩短间隔精英DPS 10ms/级",
    "Shorten Interval Grim Reaper 10ms / level": "缩短间隔死神10ms/级",
    "Show Owned ": "显示拥有",
    "Shuriken": "手里剑",
    "Silver Pickaxe": "银镐",
    "Silver Purse": "银钱包",
    "Solid Bowl": "实心碗",
    "Speedy Boots": "快速靴子",
    "Star Shards": "星辰碎片",
    "Star Stone": "星石",
    "Sun Stone": "太阳石",
    "Tower Clock": "塔钟",
    "Tower Muscle": "塔肌",
    "Tower Spell": "塔咒",
    "Vacum Chamber": "真空室",
    "War Hammer": "战锤",
    "Wolf": "狼",
    "Yeti": "雪人",
    "Zombie": "僵尸",
    "Hard Arrow": "硬箭头",
    "Hard Gun": "硬枪",
    "Hard Knuckle": "硬指关节",
    "Hard Rune": "硬符文",
    "Hard Shuriken": "硬手里剑",
    "Hard Sword": "硬剑",
    "Hard Wand": "硬魔杖",
    "Hard Weapon": "硬武器",
    "Heavy Arrow": "重箭",
    "Heavy Gun": "重炮",
    "Heavy Knuckle": "重拳",
    "Heavy Rune": "重符文",
    "Heavy Shuriken": "重手里剑",
    "Heavy Sword": "重剑",
    "Heavy Wand": "沉重的魔杖",
    "Heroes Blade": "英雄之刃",
    "Hourglass": "滴漏",
    "Increase All Damage 15% / level": "增加所有伤害 15% / 级",
    "Increase All Gain Coin 10% / level": "增加所有增益硬币 10% / 级",
    "Increase All Weapon Damage 10% / level": "增加所有武器伤害 10% / 级",
    "Increase Artifacts Power 20% / level": "提升神器威力 20% / 级",
    "Increase Auto Clicker Damage 0.1click / level": "增加 自动点击器 伤害 0.1点击 / 等级",
    "Increase Auto Clicker Duration 3sec / level": "增加自动答题器持续时间 3 秒 / 级",
    "Increase Billionaire Damage 1% / level": "增加亿万富翁伤害 1% / 级",
    "Increase Billionaire Duration 3sec / level": "增加亿万富翁持续时间3秒/等级",
    "Increase Boss Monster Drop Coin 15% / level": "增加Boss 怪物掉落金币 15% / 等级",
    "Increase Boss Time Limit 2sec / level": "增加boss时间限制2秒/级",
    "Increase Chance Skip floor 0.2% / level": "增加跳楼几率 0.2% / 级",
    "Increase Chance To Get Double Entry in Adventure Area 0.2% / level": "增加冒险区双重进入的机会 0.2% / 级",
    "Increase Damage at Tower 10% / level": "增加塔伤害 10% / 等级",
    "Increase Elite Ability Damage 20% / level": "增加精英技能伤害20%/级",
    "Increase Firearm Elite Ability 30% / level": "增加枪械精英能力 30% / 级",
    "Increase Firearm Elite Crit Chance 0.5% / level": "增加枪械精英暴击几率 0.5% / 级",
    "Increase Firearm Elite Crit Damage 20% / level": "增加火器精英暴击伤害 20% / 级",
    "Increase Firearm Elite DPS 30% / level": "提高枪械精英DPS 30%/级",
    "Increase Firearm Weapon Damage 10% / level": "增加火器武器伤害 10% / 级",
    "Increase Gain Orbs 15% / level": "增加增益球 15% / 级",
    "Increase Grim Reaper Chance 0.1% / level": "增加死神几率 0.1% / 级",
    "Increase Grim Reaper Duration 3sec / level": "增加死神持续时间 3 秒 / 等级",
    "Increase Hero Critical Chance 0.5% / level": "增加英雄暴击率 0.5% / 级",
    "Increase Hero Critical Damage 20% / level": "增加英雄暴击伤害20%/级",
    "Increase Lucky Coin Damage 1% / level": "增加幸运币伤害 1% / 级",
    "Increase Lucky Coin Duration 3sec / level": "增加幸运币持续时间3秒/等级",
    "Increase Magic Elite Ability 30% / level": "增加魔法精英能力30%/级",
    "Increase Magic Elite Crit Chance 0.5% / level": "增加魔法精英暴击率 0.5% / 级",
    "Increase Magic Elite Crit Damage 20% / level": "增加魔法精英暴击伤害 20% / 级",
    "Increase Magic Elite DPS 30% / level": "增加魔法精英 DPS 30% / 级",
    "Increase Magic Weapon Damage 10% / level": "增加魔法武器伤害 10% / 级",
    "Increase Melee Elite Ability 30% / level": "增加近战精英能力 30% / 级",
    "Increase Melee Elite Crit Chance 0.5% / level": "增加近战精英暴击率 0.5% / 级",
    "Increase Melee Elite Crit Damage 20% / level": "增加近战精英暴击伤害 20% / 级",
    "Increase Melee Elite DPS 30% / level": "增加近战精英 DPS 30% / 级",
    "Increase Melee Weapon Damage 10% / level": "增加近战武器伤害 10% / 级",
    "Increase Normal Monster Drop Coin 15% / level": "增加普通怪物掉落硬币 15% / 级",
    "Increase Offline & Idle Time Limit 9min / level": "增加离线和空闲时间限制9分钟/级",
    "Increase Offline DPS 10% / level": "提高离线 DPS 10% / 级",
    "Increase Offline Drop Coin 10% / level": "增加离线投币10%/级",
    "Increase Pet Gain Coin 1% / level": "增加宠物获得币 1% / 级",
    "Increase Pet Gain Exp 1% / level": "增加宠物增益经验 1% / 级",
    "Increase Power Shot Damage 1% / level": "增加强力射击伤害 1% / 级",
    "Increase Power Shot Duration 3sec / level": "增加强力射击持续时间 3 秒 / 级",
    "Increase Ranged Elite Ability 30% / level": "增加远程精英能力 30% / 级",
    "Increase Ranged Elite Crit Chance 0.5% / level": "增加远程精英暴击率 0.5% / 级",
    "Increase Ranged Elite Crit Damage 20% / level": "增加远程精英暴击伤害 20% / 级",
    "Increase Ranged Elite DPS 30% / level": "增加远程精英 DPS 30% / 级",
    "Increase Ranged Weapon Damage 10% / level": "增加远程武器伤害 10% / 等级",
    "Increase Rune Elite Ability 30% / level": "增加符文精英能力 30% / 级",
    "Increase Rune Elite Crit Chance 0.5% / level": "增加符文精英暴击率 0.5% / 级",
    "Increase Rune Elite Crit Damage 20% / level": "增加符文精英暴击伤害 20% / 级",
    "Increase Rune Elite DPS 30% / level": "增加符文精英 DPS 30% / 级",
    "Increase Rune Weapon Damage 10% / level": "增加符文武器伤害 10% / 等级",
    "Increase Special Force Damage 1% / level": "增加特种部队伤害1%/级",
    "Increase Special Force Duration 3sec / level": "增加特种部队持续时间3秒/等级",
    "Increase Stealth Elite Ability 30% / level": "增加隐身精英能力 30% / 级",
    "Increase Stealth Elite Crit Chance 0.5% / level": "增加隐身精英暴击几率 0.5% / 级",
    "Increase Stealth Elite Crit Damage 20% / level": "增加隐形精英暴击伤害 20% / 级",
    "Increase Stealth Elite DPS 30% / level": "增加隐形精英 DPS 30% / 级",
    "Increase Stealth Weapon Damage 10% / level": "增加隐形武器伤害 10% / 等级",
    "Increase Sword Elite Ability 30% / level": "增加剑术精英能力30%/级",
    "Increase Sword Elite Crit Chance 0.5% / level": "增加剑精暴击几率0.5%/级",
    "Increase Sword Elite Crit Damage 20% / level": "增加剑精暴击伤害 20% / 级",
    "Increase Sword Elite DPS 30% / level": "增加剑精DPS 30%/级",
    "Increase Sword Weapon Damage 10% / level": "增加剑类武器伤害 10% / 级",
    "Increase Tower Time Limit 2sec / level": "增加塔时间限制2秒/级",
    "Iron Anvil": "铁砧",
    "Katar": "卡塔尔",
    "Long Whip": "长鞭",
    "Lucky Charm": "幸运符",
    "Lucky Scroll": "幸运卷轴",
    "Magic ": "魔法",
    "Magic Glove": "魔法手套",
    "Magic Scythe": "魔法镰刀",
    "Magic Wand": "魔法棒",
    "Magic Watch": "魔术表",
    "Magnifier": "放大镜",
    "Moon Stone": "月亮石",
    "Morning Star": "晨星",
    "owned": "拥有",
    "Pet Costume": "宠物服装",
    "Roller Blade": "滚刀",
    "Ancient Arrow": "古箭",
    "Ancient Gun": "古枪",
    "Ancient Knuckle": "古代指关节",
    "Ancient Rune": "远古符文",
    "Ancient Shuriken": "古代手里剑",
    "Ancient Sword": "古剑",
    "Ancient Wand": "远古魔杖",
    "Angel Wing": "天使之翼",
    "Bardiche": "巴迪切",
    "Battle Gloves": "战斗手套",
    "Booster Drink": "助推器饮料",
    "Chakram": "飞轮",
    "Dea": "数据包络分析",
    "Decrease Auto Clicker Cooldown 3sec / level": "减少自动答题器冷却时间 3 秒 / 级",
    "Decrease Billionaire Cooldown 7sec / level": "减少亿万富翁冷却时间 7 秒 / 等级",
    "Decrease Boss Enemy HP 1% / level": "降低 Boss 敌人生命值 1% / 级",
    "Decrease Coin Master Upgrade Fee 1% / level": "降低币主升级费用 1% / 级",
    "Decrease Elite Upgrade Fee 1% / level": "降低精英升级费用 1%/级",
    "Decrease Grim Reaper Cooldown 9sec / level": "减少死神冷却时间 9 秒 / 级",
    "Decrease Hero Upgrade Fee 1% / level": "降低英雄升级费用1%/级",
    "Decrease Lucky Coin Cooldown 6sec / level": "减少幸运币冷却时间 6 秒 / 等级",
    "Decrease Normal Enemy HP 1% / level": "降低普通敌人生命值 1% / 级",
    "Decrease Pet Adventure Time 1% / level": "减少宠物冒险时间 1% / 级",
    "Decrease Power Shot Cooldown 3sec / level": "减少 强力射击 冷却时间 3 秒 / 等级",
    "Decrease Reroll Artifact Fee 1% / level": "降低重投神器费用 1% / 级",
    "Decrease Skill Upgrade Fee 1% / level": "降低技能升级费用 1%/级",
    "Decrease Special Force Cooldown 4sec / level": "减少特种部队冷却时间 4 秒 / 级",
    "Decrease Tower Guard HP 1% / level": "降低塔卫HP 1% / 级",
    "Decrease Unlock Artifact Fee 1% / level": "降低解锁神器费用 1% / 级",
    "Decrease Upgrade Artifact Fee 1% / level": "降低升级神器费用1%/级",
    "Decrease Weapon Upgrade Fee 1% / level": "降低武器升级费 1% / 级",
    "Demon": "恶魔",
    "Demon Bell": "魔铃",
    "Demon Eye": "恶魔之眼",
    "Demon Wing": "恶魔之翼",
    "Devil": "魔鬼",
    "Double Arrow": "双箭头",
    "Double Blade": "双刀片",
    "Double Gun": "双枪",
    "Double Knuckle": "双指关节",
    "Double Rune": "双符文",
    "Double Shuriken": "双手里剑",
    "Double Sword": "双剑",
    "Double Wand": "双魔杖",
    "Drake": "德雷克",
    "Earth Stone": "土石",
    "Echidna": "针鼹",
    "Eden Scroll": "伊甸卷轴",
    "Energy Bar": "能量棒",
    "Fenrir": "芬里尔",
    "Fox": "狐狸",
    "Fruit Seeds": "水果种子",
    "Gargoyle": "石像鬼",
    "Gekko": "壁虎",
    "Ghost": "鬼",
    "Ghoul": "食尸鬼",
    "Golden Pickaxe": "金镐",
    "Golden Purse": "金色钱包",
    "Golden Ticket": "金票",
    "Golden Watch": "金表",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Nine Tail": "九尾",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'Gityx': 'Gityx',
    'discord': 'discord',
    'v 0.8.6-alpha': 'v 0.8.6-alpha',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Game Login (": "游戏登录 (",
    "Hit Enemy (": "攻击敌人 (",
    "Kill Boss (": "杀死Boss (",
    "Kill Enemy (": "杀死敌人 (",
    "Online Play Time (": "在线游戏时长 (",
    "Prestige (": "声望 (",
    "Total DPC : ": "总计 DPC : ",
    "Total DPS : ": "总计 DPS : ",
    "Upgrade Artifact (": "升级神器（",
    "Upgrade Hero (": "升级英雄（",
    "Upgrade Weapon (": "升级武器（",
    "Upgrade Elite (": "升级精英（",
    "Use Skill (": "使用技能 (",
    "VIP Level :": "VIP 等级 : ",
    "Your ID :": "你的ID :",
    "24 Hours -": "24小时 -",
    "8 Hours -": "8小时 -",
    "30 Days -": "30天 -",
    "All Skill -": "所有技能 -",
    "Army HP Icon": "陆军 HP 图标",
    "Auto Clicker -": "自动点击器 -",
    "Billionaire -": "亿万富翁 -",
    "Cart of Coin (24 Hours Coin) -": "金币车（24 小时金币） -",
    "Chest of Coin (12 Hours Coin) -": "金币箱（12 小时金币） -",
    "Pouch of Coin (1 Hour Coin) -": "金币袋（1小时金币）-",
    "Bag of Coin (6 Hours Coin) -": "一袋金币（6小时金币）-",
    "Clover :": "三叶草：",
    "Current token :": "当前代币：",
    "Current Token :": "当前代币：",
    "3. Your 1st": "3. 你的第一个",
    "Gods Slot :": "众神插槽：",
    "Grim Reaper - ": "死神 -",
    "level": "等级",
    "Filter :": "筛选 ：",
    "Lucky Coin -": "幸运币 -",
    "Mandragora": "曼陀罗",
    "Permanent -": "永久 -",
    "Power Shot -": "强力射击 -",
    "Refresh In :": "刷新：",
    "Role :": "角色 ：",
    "Show Real Time DPS": "显示实时DPS",
    "Sort :": "种类 ：",
    "Special Force -": "特种部队 -",
    "Stage": "阶段",
    "Status :": "状态 ：",
    "Token :": "代币：",
    "Total Yield :": "总产量：",
    "Unlock at hero level": "在英雄级别解锁",
    "Unlock this Companion at stage": "在阶段解锁此同伴",
    "Watch Tower Lv": "瞭望塔等级",
    "Elite": "精英",
    "Gods": "神",
    "Gods Slot :": "众神插槽：",
    "Grim Reaper -": "死神 -",
    "No, Don't Clear": "不，不清除",
    "Re-roll Another": "重掷另一个",
    "Yes, Clear": "是的，清除",
    "Show All": "显示所有",
    "Unlock": "解锁",
    "Update": "更新",
    "DPC :": "DPC :",
    "DPS :": "DPS :",
    "Yield": "产出",
    "Prize :": "奖品 :",
    "Complete All (": "全部完成 (",
    "Conquer Floor (": "征服楼层 (",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "Achievement": " 成就",
    "Artifact": "  神器",
    "Auto Collapse": "  自动折叠",
    "Bank": "  银行",
    "Barracks": "  兵营",
    "Blueprint : ": "  蓝图：",
    "Cage": "  笼",
    "Check In": "  签到",
    "Clear Game": "  清除游戏",
    "Click/Sec": "  点击/秒",
    "Coin : ": "  金币 ：",
    "Coin Master": "  金币大师",
    "Coin Permanent : ": "  金币永久：",
    "Coin Temporary : ": "  金币临时：",
    "Companion": "  伴侣",
    "Contact Dev": "  联系开发",
    "Disable": "  禁用",
    "Disable (Low FPS)": "  禁用（低 FPS）",
    "DPC : ": "  DPC :：",
    "DPC Permanent : ": "  DPC 永久 :",
    "DPC Temporary : ": "  DPC 临时：",
    "DPS : ": "  DPS：",
    "DPS Permanent : ": "  DPS 永久：",
    "DPS Temporary : ": "  DPS 临时：",
    "Elite": "  精英",
    "Enable": "  使能够",
    "Enable (High FPS)": "  启用（高 FPS）",
    "Expand All": "  展开全部",
    "Export Import": "  进出口",
    "Fighter Lv ": "  战士 Lv",
    "Grind At Same Area": "  在同一区域研磨",
    "Hero": "  英雄",
    "Highest To Lowest": "  从最高到最低",
    "Hit Enemy": "攻击敌人",
    "House": "房子",
    "Join Our Discord": "  加入我们的 Discord",
    "Keep Moving Forward": "  继续前进",
    "Level Up x": "  升级 x",
    "Log": "  日志",
    "Lowest To Highest": "  最低到最高",
    "Lv ": "  等级 ",
    "Orbs : ": "  宝珠：",
    "Orbs : ": "  宝珠：",
    "Orbs Permanent : ": "  永久宝珠：",
    "Profile": "  个人资料",
    "Save Game": "  保存游戏",
    "Setting": "环境",
    "Shop": "商店",
    "Skill": "技能",
    "Statistic": "统计",
    "Strongest To Weakest": "  最强到最弱",
    "Task": "任务",
    "Thief Lv ": "盗贼吕",
    "Token : ": " 代币：",
    "Tower": "  塔",
    "Warehouse": "  仓库",
    "Weakest To Strongest": "  最弱到最强",
    "World Map": "  世界地图",
    "dwellers status (working or idle": "居民身份（工作或放置",
    "Sequence": "序列",
    "pet benefit": "宠物福利",
    "companion": "同伴",
    "Companion": "同伴",
    "Coin": "金币",
    "Elite at Soldier level 40": "精英在士兵等级 40",
    "/ 10 Sec": "/ 10 秒",
    "Elite at Fighter level 10": "战士等级 10 达到精英",
    "Equipment": "装备",
    "Gear": "齿轮",
    "Orbs": "宝珠",
    "Soul": "灵魂",
    "Spirit Stone": "精神石",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^(\d+):(\d+):(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^([\d\.,]+) Hour ([\d\.,]+) Min$/, '$1 小时 $2 分钟'],
    [/^Orbs x([\d\.,]+)$/, '宝珠 x$1'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Watch(.+)Tower(.+)Lv(.+)$/, '瞭望塔等级'],
    [/^ at stage ([\d\.,]+)$/, '在阶段 $1'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+)Coin Master Yield(.+)$/, '金币大师收益$1'],
    [/^(.+)Enemy was killed. Gain(.+)$/, '敌人被杀死了。 获得$1'],
    [/^Click Hit Enemy Button (.+) token$/, '点击 攻击敌人 按钮 $1 次'],
    [/^Complete all weekly task (.+) task$/, '完成所有周常任务 $1 个任务'],
    [/^Complete all monthly task (.+) task$/, '完成所有月常任务 $1 个任务'],
    [/^Complete all daily task (.+) task$/, '完成所有日常任务 $1 个任务'],
    [/^Conquer floor (.+) floor$/, '征服楼层 $1 层'],
    [/^Upgrade \- (.+) Orbs$/, '升级 \- $1 宝珠'],
    [/^Upgrade \- ([\d\.,]+)$/, '升级 \- $1'],
    [/^Cooldown Timer \- (.+) Min (.+) Sec$/, '冷却计时器 \- $1 分 $2 秒'],
    [/^Cooldown Timer \- (.+) Sec$/, '冷却计时器 \- $1 秒'],
    [/^Click to Stop \- (.+) Sec$/, '点击停止 \- $1 秒'],
    [/^Next Reward \- (.+) Token$/, '下一个奖励 \- $1 代币'],
    [/^Login to the game (.+) day$/, '登录游戏 $1 天'],
    [/^Welcome Back (.+)\nYou are idle for (.+) Min (.+) Sec\nYou are killing (.+) Enemies\nAnd you got (.+) Coins$/, '欢迎回来 $1\n你放置了 $2 分钟 $3 秒\n你杀死了 $4 敌人\n你得到了 $5 金币'],
    [/^Welcome Back (.+)\nYou are offline for (.+) Min (.+) Sec\nYou are killing (.+) Enemies\nAnd you got (.+) Coins$/, '欢迎回来 $1\n你离线了 $2 分钟 $3 秒\n你杀死了 $4 敌人\n你得到了 $5 金币'],
    [/^Welcome Back (.+)\nYou are idle for (.+) Sec\nYou are killing (.+) Enemy\nAnd you got (.+) Coins$/, '欢迎回来 $1\n你放置了 $2 秒\n你杀死了 $3 敌人\n你得到了 $4 金币'],
    [/^Welcome Back (.+)\nYou are idle for (.+) Sec\nYou are killing (.+) Enemy\nAnd you got (.+)$/, '欢迎回来 $1\n你放置了 $2 秒\n你杀死了 $3 敌人\n你得到了 $4'],
    [/^Welcome Back (.+)\nYou are idle for (.+) Sec\nYou are killing (.+) Enemies\nAnd you got (.+) Coins$/, '欢迎回来 $1\n你放置了 $2 秒\n你杀死了 $3 敌人\n你得到了 $4 金币'],
    [/^Welcome Back (.+)\nYou are offline for (.+) Sec\nYou are killing (.+) Enemy\nAnd you got (.+)$/, '欢迎回来 $1\n你离线了 $2 秒\n你杀死了 $3 敌人\n你得到了 $4'],
    [/^(.+)Next(.+)Skill(.+)at(.+)stage(.+)$/, '下一个技能在阶段 $5'],
    [/^lv (.+) Urumi for (.+) Orb$/, '等级 $1 乌鲁米 获得 $2 宝珠'],
    [/^Online time play (.+) mins$/, '在线游戏 $1 分钟'],
    [/^Run a prestige (.+) times$/, '运行声望 $1 次'],
    [/^Use any skill (.+) times$/, '使用任意技能 $1 次'],
    [/^Upgrade any artifact (.+) times$/, '升级任意神器 $1 次'],
    [/^Upgrade elite level (.+) lv$/, '升级精英等级 $1 级'],
    [/^Upgrade weapon level (.+) lv$/, '升级武器等级 $1 级'],
    [/^Upgrade hero level (.+) lv$/, '升级英雄等级 $1 级'],
    [/^Kill normal monster (.+) times$/, '杀死普通怪物 $1 次'],
    [/^Kill boss monster (.+) times$/, '杀死Boss怪物 $1 次'],
    [/^Fighter \- Level (.+) \- DPS (.+)\nThief \- Level (.+) \- DPS (.+)\nSoldier \- Level (.+) \- DPS (.+)$/, '战士 \- $1 级 \- DPS $2\n盗贼 \- $3 级 \- DPS $4\n士兵 \- $5 级 \- DPS $6'],
    [/^Fighter \- Level (.+) \- DPS (.+)\nThief \- Level (.+) \- DPS (.+)$/, '战士 \- $1 级 \- DPS $2\n盗贼 \- $3 级 \- DPS $4'],
    [/^\[(.+) Kingdom\]$/, '\[$1 王国\]'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) Token$/, '$1 代币'],
	[/^([\d\.,]+) Sec$/, '$1 秒'],
	[/^([\d\.,]+) Slot$/, '$1 插槽'],
	[/^([\d\.,]+) Ticket$/, '$1 门票'],
	[/^Day ([\d\.,]+)$/, '天数 $1'],
	[/^([\d\.,]+) Min ([\d\.,]+) Sec$/, '$1 分 $2 秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(.+)Soldier(.+)Lv(.+)$/, '士兵等级：'],
    [/^(.+)Fighter(.+)Lv(.+)$/, '战士等级：'],
    [/^(.+)Thief(.+)Lv(.+)$/, '盗贼等级：'],
    [/^(.+)DPS Permanent(.+):(.+)$/, '永久DPS：'],
    [/^(.+)DPC Permanent(.+):(.+)$/, '永久DPC：'],
    [/^(.+)Orbs Permanent(.+):(.+)$/, '永久宝珠：'],
    [/^(.+)DPS Temporary(.+):(.+)$/, '临时DPS：'],
    [/^(.+)DPC Temporary(.+):(.+)$/, '临时DPC：'],
    [/^(.+)Orbs Temporary(.+):(.+)$/, '临时宝珠：'],
    [/^(.+)Coin Temporary(.+):(.+)$/, '临时金币：'],
    [/^(.+)Coin Permanent(.+):(.+)$/, '永久金币：'],
    [/^(.+)DPC(.+):(.+)$/, 'DPC：'],
    [/^(.+)DPS(.+):(.+)$/, 'DPS：'],
    [/^(.+)Token(.+):(.+)$/, '代币：'],
    [/^(.+)Orbs(.+):(.+)$/, '宝珠：'],
    [/^(.+)Gear(.+):(.+)$/, '齿轮：'],
    [/^(.+)Coin(.+):(.+)$/, '金币：'],
    [/^(.+)Blueprint(.+):(.+)$/, '蓝图：'],

]);